# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "hashicorp/precise64"
  config.vm.provision "shell", privileged: false, path: "bootstrap.sh"

  # Port forwarding
  # Swift:
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  # Keystone:
  config.vm.network "forwarded_port", guest: 5000, host: 5000
  # Keystone admin:
  config.vm.network "forwarded_port", guest: 35357, host: 35357

end
